# Generated by Django 3.2.4 on 2023-11-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=60, unique=True)),
                ('telefono', models.CharField(max_length=11)),
                ('mensaje', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
