# Generated by Django 3.2.4 on 2023-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido_p', models.CharField(max_length=60)),
                ('apellido_m', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=60)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
    ]
