# Generated by Django 3.2.4 on 2023-10-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='pregunta3',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='pregunta4',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='pregunta5',
            field=models.CharField(max_length=1500),
        ),
    ]
