# Generated by Django 3.2.4 on 2023-10-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_m',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido_p',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
