# Generated by Django 3.2.4 on 2023-10-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231020_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='pregunta6',
            field=models.CharField(max_length=30),
        ),
    ]
